### Request to register a user.
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "fullName": "John Anderson",
    "email": "johnander.dev@gmail.com",
    "password": "12345678",
    "cpf": "121.144.153-21",
    "cnpj": "90.272.675/0001-82",
    "userType": "COMMON"    
}

### Request to authenticate a user.
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "johnander.dev@gmail.com",
    "password": "12345678"  
}
