# User creation
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "fullName": "bubu",
    "email": "joana@gmail.com",
    "password": "12345678",
    "cpf": "121.144.153-21",
    "userType": "COMMON"    
}

